#!/usr/bin/env bash
#displays number 1 to 100 in list format
#displays fizz, buss, fizzbuzz repectively as multiples of 3,5 and 3&5

for num in {1..100}
do
    if (( num % 3 == 0 && num % 5 == 0 ))
    then
        echo "FizzBuzz"
    elif (( num % 3 == 0 ))
    then
        echo "Fizz"
    elif (( num % 5 == 0 ))
    then
        echo "Buzz"
    else
        echo "$num"
    fi
done
