#!/usr/bin/env bash
#loops and displys diffent string in 4th and 8th iteration

count=0

while [$count -lt 10 ]
do
    if [ $count -eq 3 ]
    then
        echo "bad luck"
    elif [ $count -eq 7 ]
        echo "good luck"
    else
        echo "Best School"
    fi
    (( count++ ))
done
