#!/usr/bin/env bash
#displays number for 1-20
#displays strings in 4th, 9th, and 17th iteration

count=1

while [ $count -lt 20 ]
do
    echo "$count"
    case $count in
        "4") echo "bad luck from China";;
        "9") echo "bad luck from Japan";;
        "17") echo "bad luck from Italy";;
    esac
    (( count++ ))
done
